server:
  port: 10011
spring:
  application:
    name: birth-event-simple-consumer

  cloud:
    function:
      definition: readAndLog
    stream:
      bindings:
        readAndLog-in-0:
          destination: birth.register.avro
          group: birth-event-simple-consumer-group-${random-uuid}
          consumer:
            use-native-decoding: true
      kafka:
        bindings:
          readAndLog-in-0:
            consumer:
              startOffset: earliest
              resetOffsets: true
              configuration:
                key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
                value.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
                schema.registry.url: http://localhost:8081
                specific.avro.reader: true

        binder:
          brokers: localhost:9092
          configuration:
            schema.registry.url: http://localhost:8081

  management:
    endpoints:
      web:
        exposure:
          include: health,info,metrics,env,beans
    endpoint:
      health:
        show-details: always

  logging:
    level:
      root: INFO
